# Pytorch 
|__Functions__|__Descriptions__|
|:-----|:--------|
torch.empty()|creates uninitailized tensor
torch.rand()| creates tensor with elements random between 0 and 1 with uniform distribution
torch.zeros | creates tensor with 0 elements
torch.tensor() | creates tensor from given elements
a.new_empty()/a.new_ones()/torch.rand_like(a, )| creates tensor with property similar to tensor __a__
x.size()| shows the size of the tensor x
a+b / torch.add(a,b) / a.add(b) / torch.add(a,b, result=out) | add tensors a and b
a.add_(b) | add tensor b to tensor a inplace
__Any operation that mutates a tensor in place is post-fixed with an a _ like in x.copy_(y), x.t_() will change x__
x.copy_(y) | copies y inplace into x
x.t_() | transpose x inplace
x.view() | return tensor in another shape passed as an argument
x.item() | __Return one element tensor to a python value__
b=a.numpy() | change the tensor to numpy array
a=torch.from_numpy(a) | tensor from numpy array
device = torch.device("cuda") / y = torch.ones_like(x, device=device) / x.to(device) / x.to("cpu", torch.double) | Move the tensor between cpu and gpu

In [1]:
import torch


In [2]:
x = torch.empty(5,3)
print(x)
print(x.shape)

tensor([[ 2.7380e-20,  4.5688e-41,  2.7380e-20],
        [ 4.5688e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  2.8026e-45],
        [ 0.0000e+00, -6.2445e-08,  4.5687e-41],
        [-3.5466e-15,  3.0861e-41,         nan]])
torch.Size([5, 3])


In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.8102, 0.8560, 0.8579],
        [0.7475, 0.6144, 0.1760],
        [0.0621, 0.6057, 0.2172],
        [0.9617, 0.4239, 0.2645],
        [0.4422, 0.4630, 0.0805]])


In [4]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5,3])
print(x)
print(x.shape)

tensor([5.5000, 3.0000])
torch.Size([2])


In [6]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.4315,  0.5470,  1.3529],
        [-0.3887, -0.2623,  0.5266],
        [-1.1585, -0.0649, -0.9278],
        [ 0.2952, -0.3721, -0.1570],
        [ 1.2015, -0.3277,  1.7006]])


In [8]:
print(x.size())

torch.Size([5, 3])


In [9]:
print(x+x)
print(torch.add(x,x))

tensor([[-0.8630,  1.0940,  2.7057],
        [-0.7773, -0.5246,  1.0532],
        [-2.3170, -0.1299, -1.8556],
        [ 0.5905, -0.7442, -0.3139],
        [ 2.4029, -0.6554,  3.4012]])
tensor([[-0.8630,  1.0940,  2.7057],
        [-0.7773, -0.5246,  1.0532],
        [-2.3170, -0.1299, -1.8556],
        [ 0.5905, -0.7442, -0.3139],
        [ 2.4029, -0.6554,  3.4012]])


In [11]:
result = torch.empty(5,3)
print(result)
torch.add(x,x, out=result)
print(result)

tensor([[-1.5147e-14,  3.0861e-41,  2.7057e+00],
        [-7.7731e-01, -5.2464e-01,  1.0532e+00],
        [-2.3170e+00, -1.2988e-01, -1.8556e+00],
        [ 5.9046e-01, -7.4418e-01, -3.1395e-01],
        [ 2.4029e+00, -6.5539e-01,  3.4012e+00]])
tensor([[-0.8630,  1.0940,  2.7057],
        [-0.7773, -0.5246,  1.0532],
        [-2.3170, -0.1299, -1.8556],
        [ 0.5905, -0.7442, -0.3139],
        [ 2.4029, -0.6554,  3.4012]])


In [13]:
y= torch.ones_like(x)
print(y)
y.add_(x)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 0.5685,  1.5470,  2.3529],
        [ 0.6113,  0.7377,  1.5266],
        [-0.1585,  0.9351,  0.0722],
        [ 1.2952,  0.6279,  0.8430],
        [ 2.2015,  0.6723,  2.7006]])


In [14]:
print(x)
print(x[:,1])

tensor([[-0.4315,  0.5470,  1.3529],
        [-0.3887, -0.2623,  0.5266],
        [-1.1585, -0.0649, -0.9278],
        [ 0.2952, -0.3721, -0.1570],
        [ 1.2015, -0.3277,  1.7006]])
tensor([ 0.5470, -0.2623, -0.0649, -0.3721, -0.3277])


In [16]:
x = torch.randn(4,4)
y = x.view(16)
z=x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
x= torch.randn(1)
print(x)
print(x.item())

tensor([2.8195])
2.81954026222229


In [25]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [26]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [27]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [28]:
a + 1

tensor([3., 3., 3., 3., 3.])

In [30]:
import numpy as np
a =  np.ones(5)
b = torch.from_numpy(a)
np.add(a,1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [33]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x=x.to(device)
    z=x+y
    print(z)
    print(z.to("cpu", torch.double))

In [38]:
a
print(a.add(b))

tensor([4., 4., 4., 4., 4.], dtype=torch.float64)


In [44]:
a=a.view(1,-1)

In [45]:
a.t_()

tensor([[3.],
        [3.],
        [3.],
        [3.],
        [3.]], dtype=torch.float64)

In [47]:
a.t()

tensor([[3., 3., 3., 3., 3.]], dtype=torch.float64)